### ISSUE TITLE
Unique types

### ISSUE THREAD

**Issue by arvislacis** [skripteria/wn-snowflake-plugin#17]
Maybe I am wrong but I didn't find that `skripteria_snowflake_types` table's column `name` has any value constrain/validation related to uniqueness. As `name` column is primary used to identify different types and assign them to SF key elements then, in my opinion, there should be some kind of validation at least in `Type` model.

In ideal case there should be unique constrain in DB table and in Laravel model. This would avoid situations when, for example, just by accident someone wants to declare new type with already existing name etc.

**Comment by skripteria** [comment]
Actually I thought a lot about this problem but I couldnt find a satisfying solution to it.
When I was reading this now I had an idea for a solution that would work for conficts within pages:
We could add a field where we store the (base)filename of the page and add a constraint that the combination of basefilename / snowflake key must be unique.

This wouldnt help with layouts since the keys of any page could conflict a layout key. Maybe adding another field carring just layout_keys for constraint checks? 

Yes, it I would be great if we can find a way!

**Comment by arvislacis** [comment]
There is no need to implement new field or functionality... You just need to add new DB migration for `skripteria_snowflake_types` table which makes `name` column unique and add unique validation rule in `Type` model, that's all.

**Comment by arvislacis** [comment]
Side note  - when you publish new version of plugin, you also need to update https://github.com/skripteria/wn-snowflake-plugin/blob/main/updates/version.yaml so also in the Winter's plugin back-end it's recognized with new version. Currently the plugin back-end tells it's `1.0.1` version because `version.yaml` has no entry for `1.0.2`.

**Comment by skripteria** [comment]
Looks like you are more familiar with Laravel stuff than I am :) 
Can you do a PR on it?

**Comment by arvislacis** [comment]
Ok, I will look at this right now. :)

**Comment by skripteria** [comment]
And for the version.yaml , yes I simply had forgotten about it this time (and was angry with myself when I realized it)

**Comment by arvislacis** [comment]
Added constrains in https://github.com/skripteria/wn-snowflake-plugin/pull/20

I think that we were talking about different kind of unique checks. Your was more about Snowflake keys and elements, mine was only about `skripteria_snowflake_types` table and nothing else. :)

**Comment by skripteria** [comment]
You are right, I had been thinking the wrong way here, sorry for the confusion ...
